[versions]
jdk = "21"
androidx-activity = "1.10.1"
android-plugin = "8.12.1"
android-test-core = "1.7.0"
dagger = "2.55"
hilt-navigation-compose = "1.2.0"
android-test-junit = "1.2.1"
junit = "4.13.2"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.30"
compose-bom = "2025.04.00"
kotlinx-coroutines-android = "1.9.0"
navigation-compose = "2.8.9"
android-test-rules = "1.6.1"
truth = "1.4.2"

[libraries]
androidx-test-core = { module = "androidx.test:core", version.ref = "android-test-core" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "android-test-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "android-test-rules" }
androidx-activityx = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
junit-junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
dagger-hilt-android = { id = "dagger.hilt.android.plugin", version.ref = "dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
